[package]
name = "path_router"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "path_router"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.32.1"
# path-router = "0.2.1"
